### ISSUE TITLE
Undefined index: wrap at Psalm/Internal/Analyzer/Statements/Expression/Fetch/StaticPropertyFetchAnalyzer.php:318

### ISSUE THREAD

**Issue by AlbinoDrought** [psalm/psalm-plugin-laravel#94] opened 2020-07-13 17:29 UTC
**Describe the bug**

I have some code that Psalm okays when `psalm/plugin-laravel` is disabled. When `psalm/plugin-laravel` is enabled, I get an `Undefined index: wrap` error. Full repro at https://github.com/AlbinoDrought/repro-psalm-laravel-undefined-index

I have this resource:

```php
<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 * @property-read \App\User $resource
 */
class User extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->resource->id,
            'name' => $this->resource->name,
        ];
    }
}
```

I have this controller:

```php
<?php

namespace App\Http\Controllers;

use App\Http\Resources\User as UserResource;
use App\User;

class UserController extends Controller
{
    public function __construct()
    {
        UserResource::$wrap = 'items';
    }

    public function show(User $user)
    {
        return new UserResource($user);
    }
}
```

I see

```
Getting /app/app/Http/Controllers/UserController.php
Analyzing /app/app/Http/Controllers/UserController.php

   ErrorException 

  Undefined index: wrap

  at vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/StaticPropertyFetchAnalyzer.php:318
    314|             }
    315|         }
    316| 
    317|         $class_storage = $codebase->classlike_storage_provider->get($declaring_property_class);
  > 318|         $property = $class_storage->properties[$prop_name];
    319| 
    320|         if ($var_id) {
    321|             if ($property->type) {
    322|                 $context->vars_in_scope[$var_id] = \Psalm\Internal\Type\TypeExpander::expandUnion(
```

The `Undefined index: $wrap` error is triggered by `UserResource::$wrap = 'items';`.

I have a full repro repository at https://github.com/AlbinoDrought/repro-psalm-laravel-undefined-index

**Impacted Versions**

```
barryvdh/laravel-ide-helper           v2.7.0    Laravel IDE Helper, generates correct PHPDocs for all Facade classes, to improve auto-completion.
fruitcake/laravel-cors                v1.0.6    Adds CORS (Cross-Origin Resource Sharing) headers support in your Laravel application
laravel/framework                     v7.19.1   The Laravel Framework.
laravel/tinker                        v2.4.1    Powerful REPL for the Laravel framework.
psalm/plugin-laravel                  v1.3.1    A Laravel plugin for Psalm
vimeo/psalm                           3.12.2    A static analysis tool for finding errors in PHP applications
```

**Additional context**

For what it's worth, PHPStorm detects the `$wrap` property:

![image](https://user-images.githubusercontent.com/852873/87334547-ab676b00-c4f3-11ea-93cc-19f15a14d1e5.png)

EDIT: Still occurs with `psalm/plugin-laravel:1.4.2` and `vimeo/psalm:4.4.1`, updated repro and added Github Actions https://github.com/AlbinoDrought/repro-psalm-laravel-undefined-index/actions

**Comment by mr-feek** [comment] 2020-07-13 17:30
Thanks @AlbinoDrought for all the details, especially the repro. I'll try to take a look at this later today!

**Comment by AlbinoDrought** [comment] 2020-07-13 18:59
Additionally, Psalm exits with a successful exit code when this happens (CI thinks everything is alright, keeps going) 

![image](https://user-images.githubusercontent.com/852873/87342548-4bc38c80-c500-11ea-9819-fb9c736ab779.png)

This is probably related to Psalm instead of this plugin though

**Comment by mr-feek** [comment] 2020-07-14 00:13
This sure is interesting. I can repro it in your repo for sure, but I can't reproduce it in the test suite for this plugin. I'll continue digging.

**Comment by mr-feek** [comment] 2020-07-14 00:52
When I remove `facade/ignition` as a dependency, there are no errors. It's something to do with that.

**Comment by mr-feek** [comment] 2020-07-14 01:47
Still debugging, but I don't think  the container is happy with https://github.com/facade/ignition/blame/3da36c423bd3edbc77baf09f4d942a9264b4eeec/src/DumpRecorder/DumpRecorder.php#L27-L29

**Comment by mr-feek** [comment] 2020-07-14 02:00
There are also no issues with laravel 7.14.0. Maybe something to do with changes including/after this https://github.com/laravel/framework/commit/6018c1d18e7b764c17307c1f98d64482a00a668d#diff-67b786d2e47fe6e904a7dd17e3373295

**Comment by mr-feek** [comment] 2020-07-14 14:43
i'm still very unclear on the **why** psalm is crashing here. @muglug do you have any insights for me?

**Comment by mr-feek** [comment] 2020-07-14 14:48
When I disable laravels exception handler (comment out `\Illuminate\Foundation\Bootstrap\HandleExceptions::class,` in `Illuminate\Foundation\Console\Kernel.php`

```
./vendor/bin/psalm app/Http/Controllers/UserController.php --debug-by-line
Scanning files...
Analyzing files...

PHP Notice:  Undefined index: wrap in /Users/fiachra/repos/repro-psalm-laravel-undefined-index/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/StaticPropertyFetchAnalyzer.php on line 318
Notice: Undefined index: wrap in /Users/fiachra/repos/repro-psalm-laravel-undefined-index/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/StaticPropertyFetchAnalyzer.php on line 318
PHP Notice:  Trying to get property 'type' of non-object in /Users/fiachra/repos/repro-psalm-laravel-undefined-index/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/StaticPropertyFetchAnalyzer.php on line 321
Notice: Trying to get property 'type' of non-object in /Users/fiachra/repos/repro-psalm-laravel-undefined-index/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/StaticPropertyFetchAnalyzer.php on line 321
░

------------------------------
No errors found!
```

**Comment by mr-feek** [comment] 2020-07-14 15:22
Doing some more step debugging through psalm, and I've gotten this far:

https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/StaticPropertyFetchAnalyzer.php#L318

This property (`$wrap`) exists in `$class_storage->inheritable_property_ids`, but not in `$class_storage->properties`, which is causing the php notice.

@muglug is this something that should be fixed in psalm, or am I doing something bad in this plugin that is messing up the classlike storage/

**Comment by mr-feek** [comment] 2021-06-21 21:08
gonna close this, it was an upstream bug

**Closed by mr-feek** 2021-06-21 21:08 UTC
Labels: bug, help wanted
