### ISSUE TITLE
Contents of models.stubphp are incomplete

### ISSUE THREAD

**Issue by Ignas2526** [psalm/psalm-plugin-laravel#123] opened 2020-12-16 11:56 UTC
**Describe the bug**
Contents of models.stubphp are incomplete. I get errors about missing model class properties. E.g. id. This was not an issue in 1.4.0 version. I don't get this issue with _ide_helper_models.php generated by barryvdh/laravel-ide-helper.

**Impacted Versions**
1.4.1 and 1.4.2

**Comment by mr-feek** [comment] 2020-12-21 03:27
Does laravel ide helper have any errors or anything? Are you able to share the code?

**Comment by azurinspire** [comment] 2021-02-16 13:27
I have same problem in fresh Laravel Jetstream project, created with:

`laravel new laravel-project --jet --teams --stack=inertia`

Installed Psalm, this plugin and ide-helper. PhpStorm is able to find User::$id from _ide_helper_models.php but Psalm is not:

![Screenshot 2021-02-16 at 14 25 35](https://user-images.githubusercontent.com/40248184/108068927-0a312c00-7063-11eb-8b50-fd17d576e6ed.png)

**Comment by eithed** [comment] 2021-06-09 19:30
In case of @azurinspire this is caused by the same bug as in https://github.com/psalm/psalm-plugin-laravel/issues/146

A workaround is to replace:

```
$table->id();
```

within migration with:

```
$table->bigIncrements('id');
```

This creates same column.

Afterwards looking at `models.stubphp` one can find that stub was correctly generated

```
namespace App\Models{
/**
 * App\Models\User
 *
 * @property int $id
 *
```

**Comment by mr-feek** [comment] 2021-06-29 04:29
I think this should be fixed now -- please reopen with code to reproduce if you are still experiencing a problem.

**Closed by mr-feek** 2021-06-29 04:29 UTC
Labels: bug
