### ISSUE TITLE
Dependency installation conflict

### ISSUE THREAD

**Issue by stanimirdim92** [psalm/psalm-plugin-laravel#125] opened 2020-12-19 12:56 UTC
**Describe the bug**
Using PHP 7.4 with composer 2. Trying to install v1.4 of this plugin.

**Impacted Versions**
barryvdh/laravel-ide-helper           v2.8.2             Laravel IDE Helper, generates correct PHPDocs for all Facade classes
barryvdh/reflection-docblock          v2.0.6            
laravel/framework                     v8.19.0            The Laravel Framework.
laravel/passport                      v10.1.0            Laravel Passport provides OAuth2 server support to Laravel.
laravel/telescope                     v4.4.0             An elegant debug assistant for the Laravel framework.
lctrs/psalm-psr-container-plugin      1.1.0              Let Psalm understand better psr11 containers
orklah/psalm-insane-comparison        v1.0.2             Detects possible insane comparison ("string" == 0) to help migrate to PHP8
vimeo/psalm                           4.3.1              A static analysis tool for finding errors in PHP applications

**Additional context**
```
 Problem 1
    - psalm/plugin-laravel v1.4.0 requires illuminate/container 5.8.* || ^6.0 || ^7.0 -> found illuminate/container[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - orchestra/testbench[v3.8.5, ..., 3.8.x-dev] require laravel/framework ~5.8.35 -> found laravel/framework[v5.8.35, ..., 5.8.x-dev] but it conflicts with your root composer.json require (^8).
    - orchestra/testbench[v3.9.3, ..., 3.9.x-dev] require laravel/framework ^6.18.0 -> found laravel/framework[v6.18.0, ..., 6.x-dev] but it conflicts with your root composer.json require (^8).
    - orchestra/testbench[v4.7.0, ..., 4.x-dev] require laravel/framework ^6.18 -> found laravel/framework[v6.18.0, ..., 6.x-dev] but it conflicts with your root composer.json require (^8).
    - orchestra/testbench[v5.5.0, ..., 5.x-dev] require laravel/framework ^7.24 -> found laravel/framework[v7.24.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^8).
    - orchestra/testbench v3.8.0 requires laravel/framework ~5.8.0 -> found laravel/framework[v5.8.0, ..., 5.8.x-dev] but it conflicts with your root composer.json require (^8).
    - orchestra/testbench v3.8.1 requires laravel/framework ~5.8.2 -> found laravel/framework[v5.8.2, ..., 5.8.x-dev] but it conflicts with your root composer.json require (^8).
    - orchestra/testbench v3.8.2 requires laravel/framework ~5.8.3 -> found laravel/framework[v5.8.3, ..., 5.8.x-dev] but it conflicts with your root composer.json require (^8).
    - orchestra/testbench[v3.8.3, ..., v3.8.4] require laravel/framework ~5.8.19 -> found laravel/framework[v5.8.19, ..., 5.8.x-dev] but it conflicts with your root composer.json require (^8).
    - orchestra/testbench[v3.9.0, ..., v3.9.1, v4.0.0, ..., v4.0.1] require laravel/framework ^6.0 -> found laravel/framework[v6.0.0, ..., 6.x-dev] but it conflicts with your root composer.json require (^8).
    - orchestra/testbench[v3.9.2, v4.2.0] require laravel/framework ^6.2 -> found laravel/framework[v6.2.0, ..., 6.x-dev] but it conflicts with your root composer.json require (^8).
    - orchestra/testbench v4.1.0 requires laravel/framework ^6.1 -> found laravel/framework[v6.1.0, ..., 6.x-dev] but it conflicts with your root composer.json require (^8).
    - orchestra/testbench[v4.3.0, ..., v4.4.1] require laravel/framework ^6.4 -> found laravel/framework[v6.4.0, ..., 6.x-dev] but it conflicts with your root composer.json require (^8).
    - orchestra/testbench[v4.5.0, ..., v4.6.0] require laravel/framework ^6.9 -> found laravel/framework[v6.9.0, ..., 6.x-dev] but it conflicts with your root composer.json require (^8).
    - orchestra/testbench v5.0.0 requires laravel/framework ^7.0 -> found laravel/framework[v7.0.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^8).
    - orchestra/testbench v5.0.1 requires laravel/framework ^7.0.1 -> found laravel/framework[v7.0.1, ..., 7.x-dev] but it conflicts with your root composer.json require (^8).
    - orchestra/testbench v5.0.2 requires laravel/framework ^7.0.6 -> found laravel/framework[v7.0.6, ..., 7.x-dev] but it conflicts with your root composer.json require (^8).
    - orchestra/testbench[v5.1.0, ..., v5.2.0] require laravel/framework ^7.1 -> found laravel/framework[v7.1.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^8).
    - orchestra/testbench[v5.3.0, ..., v5.4.0] require laravel/framework ^7.10 -> found laravel/framework[v7.10.0, ..., 7.x-dev] but it conflicts with your root composer.json require (^8).
    - fakerphp/faker[v1.9.1, ..., 1.9.x-dev] require php ^5.3.3 || ^7.0 -> your php version (8.0.0) does not satisfy that requirement.
    - psalm/plugin-laravel 1.x-dev is an alias of psalm/plugin-laravel dev-master and thus requires it to be installed too.
    - psalm/plugin-laravel[dev-master, v1.4.1, ..., v1.4.2] require orchestra/testbench ^3.8 || ^4.0 || ^5.0 || ^6.0 -> satisfiable by orchestra/testbench[v3.8.0, ..., 3.9.x-dev, v4.0.0, ..., 4.x-dev, v5.0.0, ..., 5.x-dev, v6.0.0, ..., 6.x-dev].
    - orchestra/testbench[v6.7.0, ..., 6.x-dev] require orchestra/testbench-core ^6.9.1 -> satisfiable by orchestra/testbench-core[v6.9.1, 6.x-dev].
    - orchestra/testbench v6.6.0 requires orchestra/testbench-core ^6.8 -> satisfiable by orchestra/testbench-core[v6.8.0, v6.9.0, v6.9.1, 6.x-dev].
    - orchestra/testbench v6.5.0 requires orchestra/testbench-core ^6.7 -> satisfiable by orchestra/testbench-core[v6.7.0, ..., 6.x-dev].
    - orchestra/testbench v6.4.0 requires orchestra/testbench-core ^6.6 -> satisfiable by orchestra/testbench-core[v6.6.0, ..., 6.x-dev].
    - orchestra/testbench v6.3.0 requires orchestra/testbench-core ^6.5 -> satisfiable by orchestra/testbench-core[v6.5.0, ..., 6.x-dev].
    - orchestra/testbench[v6.1.0, ..., v6.2.0] require orchestra/testbench-core ^6.1 -> satisfiable by orchestra/testbench-core[v6.1.0, ..., 6.x-dev].
    - orchestra/testbench v6.0.0 requires orchestra/testbench-core ^6.0 -> satisfiable by orchestra/testbench-core[v6.0.0, ..., 6.x-dev].
    - orchestra/testbench-core[v6.5.0, ..., 6.x-dev] require fakerphp/faker ^1.9.1 -> satisfiable by fakerphp/faker[v1.9.1, ..., v1.13.0].
    - fzaninotto/faker v1.5.0 conflicts with fakerphp/faker v1.13.0.
    - fzaninotto/faker v1.5.0 conflicts with fakerphp/faker v1.12.1.
    - fzaninotto/faker v1.5.0 conflicts with fakerphp/faker v1.12.0.
    - fzaninotto/faker v1.5.0 conflicts with fakerphp/faker v1.11.0.
    - fzaninotto/faker v1.5.0 conflicts with fakerphp/faker v1.10.1.
    - fzaninotto/faker v1.5.0 conflicts with fakerphp/faker v1.10.0.
    - fzaninotto/faker v1.5.0 conflicts with fakerphp/faker 1.12.x-dev.
    - orchestra/testbench-core[v6.0.0, ..., v6.4.1] require fzaninotto/faker ^1.9.1 -> satisfiable by fakerphp/faker[v1.9.1, v1.9.2, 1.9.x-dev].
    - Root composer.json requires fzaninotto/faker ^1 -> satisfiable by fzaninotto/faker[v1.5.0], fakerphp/faker[v1.9.1, v1.9.2, 1.9.x-dev].
    - Root composer.json requires psalm/plugin-laravel ^1.4 -> satisfiable by psalm/plugin-laravel[v1.4.0, v1.4.1, v1.4.2, 1.x-dev (alias of dev-master)].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

```

**Comment by mr-feek** [comment] 2020-12-21 03:22
@stanimirdim92 does the recommended `--with-all-dependencies` not work?

**Comment by stanimirdim92** [comment] 2020-12-21 10:57
It does. Thanks!

**Comment by mr-feek** [comment] 2020-12-21 19:20
That definitely seems to be a bug with this plugin. I'm going to close this original ticket. Please open up another with any findings or code to reproduce!

**Closed by mr-feek** 2020-12-21 19:20 UTC
Labels: bug

**Comment by HenkPoley** [comment] 2021-01-19 07:47
@stanimirdim92 did you resolve the `Cannot get method params for Illuminate\Contracts\Foundation\Application::__call` exception?

**Comment by stanimirdim92** [comment] 2021-01-21 07:02
Hi, I think it did. However, I had other issues. Currently I don't have it
installed. Will run few tests this weekend and let you know.

На вт, 19.01.2021 г. в 9:48 ч. Henk Poley <notifications@github.com> написа:

**Comment by JesterAntik** [comment] 2021-01-22 07:55
Add more case: 
Error:
```
In Pool.php line 357:
                                                                                                                                                                                                                    
  Cannot get method params for Illuminate\Contracts\Foundation\Application::__call                                                                                                                                  
  Stack trace in the forked worker:                                                                                                                                                                                 
  #0 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php(264): Psalm\Internal\Codebase\Methods->getMethodParams()                                                        
  #1 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/ExistingAtomicMethodCallAnalyzer.php(192): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::checkMethodA  
  rgs()                                                                                                                                                                                                             
  #2 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php(401): Psalm\Internal\Analyzer\Statements\Expression\Call\Method\ExistingAtomicMethodCa  
  llAnalyzer::analyze()                                                                                                                                                                                             
  #3 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(184): Psalm\Internal\Analyzer\Statements\Expression\Call\Method\AtomicMethodCallAnalyzer::analyze()  
  #4 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(148): Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer::analyze()                               
  #5 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(40): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()                                       
  #6 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php(194): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()                                    
  #7 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(129): Psalm\Internal\Analyzer\Statements\Expression\AssignmentAnalyzer::analyze()                                    
  #8 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(40): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()                                       
  #9 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(530): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()                                                          
  #10 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(172): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement()                                                           
  #11 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(421): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze()                                                                  
  #12 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClosureAnalyzer.php(203): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze()                                                                     
  #13 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(283): Psalm\Internal\Analyzer\ClosureAnalyzer::analyzeExpression()                                                  
  #14 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(40): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()                                      
  #15 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php(197): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()                               
  #16 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/CallAnalyzer.php(312): Psalm\Internal\Analyzer\Statements\Expression\Call\ArgumentsAnalyzer::analyze()                          
  #17 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/ExistingAtomicStaticCallAnalyzer.php(174): Psalm\Internal\Analyzer\Statements\Expression\CallAnalyzer::check  
  MethodArgs()                                                                                                                                                                                                      
  #18 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php(721): Psalm\Internal\Analyzer\Statements\Expression\Call\StaticMethod\ExistingA  
  tomicStaticCallAnalyzer::analyze()                                                                                                                                                                                
  #19 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticMethod/AtomicStaticCallAnalyzer.php(171): Psalm\Internal\Analyzer\Statements\Expression\Call\StaticMethod\AtomicSta  
  ticCallAnalyzer::handleNamedCall()                                                                                                                                                                                
  #20 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticCallAnalyzer.php(205): Psalm\Internal\Analyzer\Statements\Expression\Call\StaticMethod\AtomicStaticCallAnalyzer::an  
  alyze()                                                                                                                                                                                                           
  #21 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(152): Psalm\Internal\Analyzer\Statements\Expression\Call\StaticCallAnalyzer::analyze()                              
  #22 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(40): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()                                      
  #23 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(530): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()                                                         
  #24 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(172): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement()                                                           
  #25 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(421): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze()                                                                  
  #26 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1639): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze()                                                                      
  #27 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(387): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod()                                                                   
  #28 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(213): Psalm\Internal\Analyzer\ClassAnalyzer->analyze()                                                                               
  #29 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(340): Psalm\Internal\Analyzer\FileAnalyzer->analyze()                                                                                    
  #30 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(193): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}()                                                                      
  #31 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(406): Psalm\Internal\Fork\Pool->__construct()                                                                                            
  #32 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(269): Psalm\Internal\Codebase\Analyzer->doAnalysis()                                                                                     
  #33 /srv/app/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(635): Psalm\Internal\Codebase\Analyzer->analyzeFiles()                                                                            
  #34 /srv/app/vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check()                                                                                                              
  #35 /srv/app/vendor/vimeo/psalm/psalm(2): require_once('/srv/app/vendor...')                                                                                                                                      
  #36 {main}                                                                                          
```
Debug
```
...
Analyzing /srv/app/app/Http/Controllers/Auth/ForgotPasswordController.php
/srv/app/vendor/laravel/ui/auth-backend/SendsPasswordResetEmails.php:19
/srv/app/vendor/laravel/ui/auth-backend/SendsPasswordResetEmails.php:30
/srv/app/vendor/laravel/ui/auth-backend/SendsPasswordResetEmails.php:35
/srv/app/vendor/laravel/ui/auth-backend/SendsPasswordResetEmails.php:39
/srv/app/vendor/laravel/ui/auth-backend/SendsPasswordResetEmails.php:52
/srv/app/vendor/laravel/ui/auth-backend/SendsPasswordResetEmails.php:63
/srv/app/vendor/laravel/ui/auth-backend/SendsPasswordResetEmails.php:75
```

Code: 
```
protected function sendResetLinkResponse(Request $request, $response)
    {
        return $request->wantsJson() //  line 75
                    ? new JsonResponse(['message' => trans($response)], 200)
                    : back()->with('status', trans($response));
    }
```

**Comment by HenkPoley** [comment] 2021-01-22 14:18
Ref: https://github.com/laravel/ui/blob/3.x/auth-backend/SendsPasswordResetEmails.php#L66-L78

**Comment by neclimdul** [comment] 2021-02-25 18:48
If you're using the bindMethod or possibly some other methods that exist on the real container but aren't on the container interface hinted in the service provider base class this will happen. @see #125 for a test case.
