### ISSUE TITLE
Failure to install due to dependencies conflict

### ISSUE THREAD

**Issue by liviublidar** [psalm/psalm-plugin-laravel#89] opened 2020-06-22 21:15 UTC
**Describe the bug**
 Initial installation on Laravel 6.0 is not possible due to dependencies conflict. 

**Impacted Versions**
```
barryvdh/laravel-debugbar             v3.2.9       PHP Debugbar integration for Laravel
fruitcake/laravel-cors                v1.0.4       Adds CORS (Cross-Origin Resource Sharing) headers support in y...
laravel/framework                     v6.0.0       The Laravel Framework.
laravel/tinker                        v1.0.10      Powerful REPL for the Laravel framework.
vimeo/psalm                           3.12.0       A static analysis tool for finding errors in PHP applications
```
**Additional context**

```composer require --dev psalm/plugin-laravel
Using version ^1.3 for psalm/plugin-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for composer/semver (locked at 3.0.0) -> satisfiable by composer/semver[3.0.0].
    - psalm/plugin-laravel 1.x-dev requires barryvdh/laravel-ide-helper ^2.7 -> satisfiable by barryvdh/laravel-ide-helper[v2.7.0].
    - psalm/plugin-laravel v1.3.0 requires barryvdh/laravel-ide-helper ^2.7 -> satisfiable by barryvdh/laravel-ide-helper[v2.7.0].
    - Conclusion: don't install barryvdh/laravel-ide-helper v2.7.0
    - Installation request for psalm/plugin-laravel ^1.3 -> satisfiable by psalm/plugin-laravel[1.x-dev, v1.3.0].
```

**Comment by mr-feek** [comment] 2020-06-23 00:30
Hrm, I don't know much about these composer packages, but it looks like the issue is because you have `composer/semver` locked at `3.0`, and laravel-ide-helper (which this package depends on), requires `composer/composer` `^1.6`

@liviublidar what version of composer are you using? Is there a public repo that I can reproduce with?

I think this issue will need to be resolved over at laravel-ide-helper if I'm understanding correctly.

**Comment by mr-feek** [comment] 2020-06-23 16:14
@liviublidar I believe the issue might be resolved now, i opened a PR over at ide-helper. You'll need to update that to the latest dev-master while installing this package, care to give it a shot?

**Comment by liviublidar** [comment] 2020-06-24 15:09
@mr-feek Sure, sorry for replying so late, got caught up in other chores. Will try it out today/tomorrow.

**Comment by netcode** [comment] 2020-07-08 10:05
The problem exists because 
Psalm it self use `composer/semver 3.0`
and Laravel-ide-helper v2.7 is using `composer/composer 1.10` which requires `composer/semver ^1.0` .

I think we need to update the requirements here to point to `Laravel-ide-helper` dev-master instead of v2.7 until they release official version

**Comment by mr-feek** [comment] 2020-07-25 17:58
`dev-master` should be in a good state, im going to close this

**Closed by mr-feek** 2020-07-25 17:58 UTC
Labels: bug
