### ISSUE TITLE
Use config('auth.providers.user') for return type of Auth::user() and Request::user()

### ISSUE THREAD

**Issue by caugner** [psalm/psalm-plugin-laravel#184] opened 2021-07-13 13:04 UTC
**Is your feature request related to a problem? Please describe.**

According to PHPDoc:

* `Illuminate\Support\Facades\Auth::user()` returns `\Illuminate\Contracts\Auth\Authenticatable|null`
* `Illuminate\Http\Request::user()` returns `mixed`

However, if `providers.users.driver` is set to `eloquent` in `config/auth.php`, they return the model configured in `providers.users.model`, which [defaults to](https://github.com/laravel/laravel/blob/c636fd0f678008caf30683833b740fb6f31d9de6/config/auth.php#L68-L72):

```php
    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],
```

**Describe the solution you'd like**
The Psalm plugin should use that config to determine (and narrow) the return type of `Auth::user()` and `$request->user()`.

**Describe alternatives you've considered**
(None.)

**Additional context**
(None.)

**Comment by mr-feek** [comment] 2021-07-13 16:29
Huh, I thought ide-helper already provided this functionality!

**Comment by tm1000** [comment] 2022-01-28 20:28
@mr-feek it does but the issue is that Psalm gets confused and also reads `\Illuminate\Contracts\Auth\Authenticatable|null`

**Comment by mr-feek** [comment] 2022-06-17 16:08
I think I'm going to add in some dynamic analysis to stricten the return type of the `config` helper -- right now using the config helper can result in `PossiblyInvalidCast`. 

We already do dynamic analysis for resolving container types -- it could also prove beneficial for resolving this issue

**Comment by tm1000** [comment] 2022-06-24 21:43
@mr-feek sounds good to me I haven't gotten back to this because the tests are extremely complicated for this. I only learned how they worked from the work on the 9.x release so I think I can actually get back to written a test here

**Comment by mr-feek** [comment] 2022-06-24 22:13
Feel free to take a look at https://github.com/psalm/psalm-plugin-laravel/pull/229 and https://github.com/nunomaduro/larastan/blob/master/src/Concerns/LoadsAuthModel.php for inspiration!

**Closed** 2023-03-04 19:25 UTC
Labels: enhancement
